{% set name = "progress_reporter" %}
{% set pypi_name = name.replace('_', '-') %}
{% set version = "2.0" %}
{% set sha256 = "3268b3281f06894643073dae5205e41e2a3b3811b7a3c34e39ece8b4107e9a7b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ pypi_name}}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - setuptools
    - pip
    - python

  run:
    - python

test:
  imports:
    - progress_reporter

about:
  home: https://github.com/marscher/progress_reporter
  license: MIT
  license_file: LICENSE.rst
  summary: 'Python interface for progress reporting'
  description: |
    progress reporter enables developers to simply report several working steps
    via an easy to use interface. The progress bar visualisation backends are 
    implemented for console and Jupyter notebooks.
  doc_url: https://github.com/marscher/progress_reporter
  dev_url: https://github.com/marscher/progress_reporter 

extra:
  recipe-maintainers: 
    - marscher
