{% set name = "progress_reporter" %}
{% set pypi_name = name.replace('_', '-') %}
{% set version = "1.4" %}
{% set sha256 = "59430a9f4c8f9f3d80259b439ae0e9021bca8d05ecb940f02187915c04acdd48" %}

package:
  name: {{ name|lower }} 
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ pypi_name}}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - setuptools

  run:
    - tqdm
    - python

test:
  imports:
    - progress_reporter

about:
  home: https://github.com/marscher/progress_reporter
  license: MIT
  license_file: LICENSE.rst
  summary: 'Python interface for progress reporting'
  description: |
    progress reporter enables developers to simply report several working steps
    via an easy to use interface. The progress bar visualisation backends are 
    implemented for console and Jupyter notebooks.
  doc_url: https://github.com/marscher/progress_reporter
  dev_url: https://github.com/marscher/progress_reporter 

extra:
  recipe-maintainers: 
    - marscher
