travis:
  secure:
    BINSTAR_TOKEN: JdlUwcZkEktWjXN10mLsUkuWI874TZ6lwJYvaPUpdbuQKLk9u/hG4/ptLiFZmRX3qDe5HpjheTMLLl8cBaydBRlpEoTadIPE+9kr40rOWy0+20gDrdCK13v/si+L/YKdOircWKbeN04zS1W5XCnc99JzQ5AlP7UaG7qMtNoWV7qSF5Q7acPJACewYsbCJEYFCEcV7FaMBl6t6dNN/XHVupqW3nx+2zouIsMccHKKdtjkao5MAaB+9lIJ30g738EfoZV/NM6NT4DijHeV5wQIuGAUnOE8cpVWm3xtACRbY8aJRs1xIvu78SKoCZRDhGZZ2YpGF/5H8kM/kR6IQJoBMcKbQCY7naU3oMGXaDMEQL7mQZFyzO8qBEE8ne7LLhJmcOWdmK11hGo9N26w0sSOxe0Do5cn3w00ro2IYsFLCj/J4IE8MscpxCeSSa0d5IrLug0ZvA1VFjpsOKexa4Cf8JTSMR27bPLqKoRPUqdOHDuk6tJnith52uTcRo72xmtRXIPHanmsHGlDnjD+NUJdTJ23O8hkEynJas5jVzM8lmjSP3H3vBvezx95/w1XJNPVssYU7D1qaN+P1k1pURtQTsGZQN/mnEZr+k2r2OlF0fMhZaRpeyrKOaqS3uZCT+DnPVnUV366vzoRQDvhgUOYnlRwqR1TCO1Jh5/e8P5mNzI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
