travis:
  secure:
    BINSTAR_TOKEN: Bhyzn/l8vBlHvWQg93pzELeHMAx2E8qjBgpggJE1JHOL6SwL5FvmZj2rRw28wKOfKsOLSDZ0uLVSPtEtHTG4UlmCzYCWpWOP7LV7xqnlhqGGn9rzdTysg0OBMKXgbyKb5EJQ1c+2SqBpRFsQKZFEPO2iyaN2uRHbnP6AiDI/KFtNXG4KU2/i6upRXavdX6kxg/jYCYigWUT8vcPQa0RHDKYnlOhizAyTRIxxri3R1223SI2Fq6HVvfbYcsAInr/mMH6dkYkfCkHNCZmC0a1ZBuFWSVjyE3FmfCha9ROPH1+PnJ/ncfQkC/08xQQyY8LoryoZTj4xKU21eJ4AuunNy6eV0xZlz5tBMNS/jYwZhxqA6it1Bq3YodEjc4SAW6Xuw0tOZPRXEmRzvaTrbdEstHcbayInpBFnLZxhP3Kqn/b/2VfNMMGCa4iq/LZd1ajih3d9OjyNFkX5czGpHzAUyMO5W5SffxFK8okVZyZFFHc/TXJvaZeSuiYLsdAWR1A5S50yGDhYFyZopbflW7vvE+5ACjBfWIue9Yk+IoSStH2+VgItemKgW02X+mDvTtKT1q9uVyFBNwrWYZltF3pVKpwOqf8SLs8RAt6PS6RyMlUJgCCcc4APZqRuadz3HdMkOfgiYNqNLi2CgXlYq49T38GfkmgxMcI40oBT0q39fRM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
